### ISSUE TITLE
Can we use linux-image-for-odroid-xu3 even for odroid xu4?

### ISSUE THREAD

**Issue by ezamorag** [AutoModelCar/AutoModelCarWiki#1]
I installed the image (linux-image-for-odroid-xu3) in a SD micro card, following and adapting the steps in the wiki "Flashing the eMMC". However, the odroid xu4 did not boot from the SD micro card. 
Even I turned the switch to SDmicro in the odroid board and during the installation everything was ok. 
I did this steps:
1. Install Term::ReadKey by typing "sudo cpan Term::ReadKey"
2. Insert the SD micro to my computer's memory slot. 
3. Figure out the path to the SD micro memory, in my case, /dev/mmcblk0
4. Install the image typing "sudo ./install.pl /dev/mmcblk0"
5. Follow the configuration steps until installation finishes. 
6. Insert the SD micro on odroid xu4 and turn the switch to SDmicro. 
7. Plug the power and wait for booting.

However, the odroid did not boot from my SD micro memory. 
What was the problem?

**Comment by ZahraBoroujeni** [comment]
I never tried the SD micro card, you have already a emmc card on the car, and you can use it, as I read emmc card is more stable than sd card!
