### ISSUE TITLE
Odroid with 16.04-kinect image does not start

### ISSUE THREAD

**Issue by gdmd** [AutoModelCar/AutoModelCarWiki#12]
Hi,

   We installed the linux-image-for-odroid-xu4-16.04-kinetic image according to the web instructions on the eMMC, previously installing the "Term::ReadKey" on host PC, and after a successful installation and configuration (at least according to the script output) the Odroid does not start. 

   Since we read the first boot may take a minute or two, we waited, but after 25-30 minutes the odroid is at the same state. After plugin the power, the fan starts, the blue led keeps blinking and if you connect a monitor to the hdmi port you see a flashing dash, but that's it.

   We re-download the image, and flashed it again using another card reader but the problem persists.

   Any suggestion?

**Comment by AutoModelCar** [comment]
As the blue led keeps blinking, it means it boots the image correctly, and everything is fine. Just make a static IP in your computer, for example 192.168.1.10 and connect through Ethernet to the Odroid. You could not use monitor because it is disabled. 

      ssh root@192.168.1.199

**Comment by gdmd** [comment]
The Static IP allows to ping the Odroid, but the ssh connection is rejected by it. I also create a wireless network called "ROS" with the password set in configuration but the Odroid is not connecting to it.

**Comment by gdmd** [comment]
We were able to recover the system after installing a previous image (the one from April). However, after several tries we were unable to load the 16.04 kinetic version. After successful installation on the emmc card, the Odroid behavior was the same, just a blinking led and response to ping but without ssh access.

I don't know is anyone else had a similar problem before when upgrading the system. Maybe a configuration step we are forgetting...

I appreciate any guidance on this problem.

**Comment by AutoModelCar** [comment]
Yes, I have the same problem in the new computer. I will update the image as soon as I find the error.

**Comment by AutoModelCar** [comment]
For now: You can try 

    $ sudo rm -rf /path/to/emmc/rootfs/*
    $ cd /path/to/emmc/rootfs
    $ sudo tar -xzf /path/to/rootfs.tgz .
    $ sync
    $ sudo umount /path/to/emmc/rootfs

**Comment by gdmd** [comment]
@AutoModelCar we tried the workaround but yet the car has the same behaviour... we will return to previous image and wait until yo upload a new one for 16.04... if you need us to test anything just let us know

Thank you for your help

**Comment by AutoModelCar** [comment]
could you test the new image here:

For the first boot maybe you need to disconnect all usb cables!

Image: `ftp://ftp.imp.fu-berlin.de/pub/autonomos/data/modelcar/linux-image-for-odroid-xu4-ubuntu-kinetic-v1.tar.gz`

and use `https://github.com/AutoModelCar/model_car/tree/version-3-kinetic` as catkin_ws

**Comment by gdmd** [comment]
Hi,

   We tried the new version and it boots correctly. However, the autostart script fails because the udev rules are not working, so the ttyLidar and ttyArduino are not created on startup. If you stop ROS, create the links manually and run manual_control again, it works fine. Attached you can find the dmesg and lsusb outputs after startup.

[start_dmesg.txt](https://github.com/AutoModelCar/AutoModelCarWiki/files/1179300/start_dmesg.txt)
[start_lsusb.txt](https://github.com/AutoModelCar/AutoModelCarWiki/files/1179301/start_lsusb.txt)

   On another topic, I am not sure if another issue is related to this system image, but when visualising the realsense data on a Host PC through ethernet connection, after 2-3 minutes the realsense_camera node fails and closes with this error on the console (manual launch on console)

[ERROR] [1455208534.956943869]: /app/camera/driver - Error calling rs_wait_for_frames ( device:0x18b550 ): 
Timeout waiting for frames.  

   Also, there is no DHCP server enabled on the Odroid, so it requires the HOST Pc to have a static IP. This is not really an issue, but I think it is worth mention it on the instructions for future users.

**Comment by AutoModelCar** [comment]
Did you use copy.sh in model_car/version-3-kinetic?

If you copy two rules files it will solve the problem :

       scp 72-serial.rules root@192.168.1.199:/etc/udev/rules.d/
       scp 71-usb-cam.rules root@192.168.1.199:/etc/udev/rules.d/

For the camera, do you have enough power?

**Comment by gdmd** [comment]
My bad, I did not pull the latest changes on the model_car repository (mine was from two days ago) so rules were not ok. Now I updated my local branch version-3-kinect and run copy.sh again and it works without problem.

Regarding the realsense, I have not delimited the problem yet. Sometimes happens after 1 minute and sometimes after 20 minutes test is working without any problem. If I have further news about it I will let you know. We are using a power adaptor you gave us at Barcelona with the proper power output.

Regarding this thread, I think you can close the issue now. Thank you very much for your support.

**Comment by AutoModelCar** [comment]
About realsense camera I hope it will not happen anymore, because we are using ros-kinetic-realsense-camera package and it should not be in local catkin_ws anymore.

**Comment by RamsesReyes** [comment]
I had the same problem, I copied boot and rootfs folders manually and the odroid worked, or at least it seems to be (the fan does not turn off anymore). My laptop connected to it by ethernet setting the ip static, but it can't ping the odroid. I set the connection as follows:
Ip: 192.168.1.190
Netmask: 255.255.255.0
Gateway: 192.168.1.1
Is that right?

Thank you for any help :)
