### ISSUE TITLE
Can't download Cross compile SDK and Compiler, the links were Error (500)

### ISSUE THREAD

**Issue by gracekk** [AutoModelCar/AutoModelCarWiki#19]
https://github.com/AutoModelCar/AutoModelCarWiki/wiki/Cross-compile
Where can find the SDK packages? The links were invalid.
https://www.dropbox.com/s/4nrvc8n8mggq4pl/sdk-20160527-0824.tar.bz2

**Comment by AutoModelCar** [comment]
We did not update the sdk for the newer version, the link is invalid for now.
