### ISSUE TITLE
Arduino code

### ISSUE THREAD

**Issue by jsaldivar1937** [AutoModelCar/AutoModelCarWiki#20]
Hi.
Where do I find the arduino code V3?

**Comment by AutoModelCar** [comment]
Which group are you belong to? 
I added you as a Collaborator to "auto_arduino_nano" private repository. 
Select branch "version-3". This branch has two main files. If your car has 21 Leds select "main.21Leds" otherwise select "main".

**Comment by jsaldivar1937** [comment]
Thanks.. 
we belong to the Universidad Autónoma de Zacatecas.

**Comment by Giovanni-frid** [comment]
Could you also add me to the repository? I belong to the CIC IPN

**Comment by AutoModelCar** [comment]
You have been added.

**Comment by jsaldivar1937** [comment]
Could you add me to the model_car directories? version 2 and version 3

**Comment by Toku11** [comment]
Could you add me to the catkin_ws and arduino code repository ? I belong to CINVESTAV

**Comment by AutoModelCar** [comment]
Done!

**Comment by JuanDanielSoto** [comment]
Could you add me to auto_arduino_nano and model_car? I belong from the Physical Institute UNAM

**Comment by AutoModelCar** [comment]
Done!

**Comment by JSBuelna** [comment]
Hi, I'm writing from the University of Guadalajara (CUCI), could you add me to "arduino code repository"?

**Comment by JesusCoyotzi** [comment]
Hi could you add me to the repositories? 
I am from the Pumas Team in the Biorobotics laboratory at UNAM.

**Comment by ubaldoruiz** [comment]
Hi, could you add me to the arduino_nano and model_car repositories? I'm a member of CICESE's team.

**Comment by luishg0111** [comment]
Hi, Could you add me to the catkin_ws and arduino V2 and V3 code repository ? I belong to Universidad Tecnológica de la Mixteca

**Comment by FrankGaLu** [comment]
Hi. Could you add me to the private repositories? I belong to Cinvestav.

Thank you

**Comment by arzola91** [comment]
Hi, Could you add me to the model_car directories please?
I'm with CINVESTAV, Gdl.

**Comment by AutoModelCar** [comment]
done

**Comment by ghost** [comment]
please add me as well

**Comment by A1000carZ** [comment]
Hello!

Could you add me to the model_car directories? version 2 and version 3

I´m with a team that participates in the next year

**Comment by sundermann** [comment]
There are no private repositories anymore, everything has been open sourced for the cars up until version 3.2.
