### ISSUE TITLE
model_car repository.

### ISSUE THREAD

**Issue by JesusCoyotzi** [AutoModelCar/AutoModelCarWiki#21]
Hi I am from the Biorobotics Team at UNAM engineering faculty.
I was told there is a new version for the workspace which we wanted to use to update our car.
On the Wiki README there is a link to https://github.com/AutoModelCar/model_car. However I am not sure if it is a broken link  or if it is a private repository, like the arduino code. 
So I wanted to know if I could be added to the repository or if the new version is available elsewhere.
Thanks in advance.

**Comment by rafabr4** [comment]
Hello, I'm having the same issue. In our team from ITESM CEM we just got the automodel car and we are trying to get it started. As far as I can see, to use the codes inside "/catking_ws_user" we need access to the "/model_car" repository, but this one is not available. Thanks.

**Comment by AutoModelCar** [comment]
It is a private repository. I could give you an access.

**Comment by Sandracm** [comment]
Hello, could you give me access to the model_car repository please? Thanks

**Comment by Sandracm** [comment]
Hello, is it possible to have the private repository?
You closed the issue unsolved.
Thanks
