### ISSUE TITLE
No image file

### ISSUE THREAD

**Issue by UrielHaile** [AutoModelCar/AutoModelCarWiki#22]
Greeting from Mexico:

We are trying to follow this guide https://github.com/AutoModelCar/AutoModelCarWiki/wiki/Flashing-the-eMMC-(AutoNOMOS-Model-v3) but the download link is broken :'(. Could you please put available the flash image again? also, we need access to the private repositories  `model_car` and `auto_arduino_nano` to complete the setup. Thank you!

**Comment by AutoModelCar** [comment]
ftp://ftp.imp.fu-berlin.de/pub/autonomos/data/modelcar/v3/system-images/

**Comment by UrielHaile** [comment]
Hey, thanks for the help!
