### ISSUE TITLE
Flash memory problem

### ISSUE THREAD

**Issue by AdonaiDV** [AutoModelCar/AutoModelCarWiki#23]
Hello. I'm Adonai, a student from Mexico. 
I'm working with the "Autonomo mini" with others students. We had some problem with the flash memory; we lost the packages. Would you help us to recover the packages? We have the first version of the car.
Thank you.

**Comment by AutoModelCar** [comment]
Hello, I added you to the private repo. And follow the link below:
https://github.com/AutoModelCar/AutoModelCarWiki/wiki/Flashing-the-eMMC

**Comment by AdonaiDV** [comment]
Thank you so much.
