### ISSUE TITLE
Odometry Control Ackerman

### ISSUE THREAD

**Issue by rafacastalla** [AutoModelCar/AutoModelCarWiki#26]
I would like to know if there is a module that is in charge of positioning the car in x and y in the 2D plane using the control of Ackerman.

**Comment by AutoModelCar** [comment]
If you mean based on the Ackerman model, the Odometry package (version 3.1) is already implement based on it.
https://github.com/AutoModelCar/model_car/blob/version-3.1-kinetic/catkin_ws/src/odometry/src/odometry_publisher.cpp

**Comment by rafacastalla** [comment]
I mean to mark a target on the x and y plane. Like, go to the point x = 100 and y = 300. And if not, how could it be implemented?

Me refiero a marcarle un objetivo en el plano x e y. Como, ve al punto x = 100 e y = 300. Y sino esta, como lo prodria implementar?

**Comment by AutoModelCar** [comment]
The fub_ controller is implemented based on the Ackerman constrains. It defines a look ahead point to make a smooth steering.
https://github.com/AutoModelCar/catkin_ws_user/tree/master/src/fub_controller

**Comment by rafacastalla** [comment]
Okay! Thanks!
