### ISSUE TITLE
How can I change the rate of publishing the realsense camera RGB topic?

### ISSUE THREAD

**Issue by ezamorag** [AutoModelCar/AutoModelCarWiki#3]
In this moment, the rate is about 7Hz. I want to increase this rate to up 30Hz, is it possible?

**Comment by AutoModelCar** [comment]
you can change the rate of camera up to 30 Hz in the launch file:
catkin_ws/src/realsense_camera/launch/includes/realsense_r200_nodelet.launch.xml
