### ISSUE TITLE
IMU gets stocked in the same value

### ISSUE THREAD

**Issue by Toku11** [AutoModelCar/AutoModelCarWiki#4]
Hi, we have been making some test holding an orientation with the value of the heading topic, everything was working good until we noticed that the value was the same when we were trying to move in slow velocity (less than 300 in motor speed), when we try to reach certain angle the measurement holds the same value in the heading topic (yaw), we already checked the yaw value directly connected via USB cable  (Arduino Terminal) and shows the same value than ROS, but when we stop the vehicle or the vehicle is moving faster apparently the IMU works again. 

We also noticed that when turn on the system the YAW angle starts with certain angle offset (between 30 and 60 degrees), all the events can be reproduced. What could be happening ? Could the IMU have some damage?  Greetings

**Comment by AutoModelCar** [comment]
IMU works fine. 
- The drift of the IMU at the beginning is a common issue to use the IMU. You should always care about the drift at the beginning and initialize your angle. 
- To calculate the angle I used the  "MPU6050_6Axis_MotionApps20.h" library. Which combined the gyroscope and accelerometer data and provide the angle. By changing the coefficient in the library, I hope you can solve the problem for the lower speed, but it may cause the problem for higher speed. 
  https://github.com/jrowberg/i2cdevlib/issues

**Comment by AutoModelCar** [comment]
Original library:
https://github.com/jrowberg/i2cdevlib/tree/master/Arduino/MPU6050

**Comment by AutoModelCar** [comment]
@Toku11  could you please use the code below to calibrate your IMU?
https://github.com/jrowberg/i2cdevlib/tree/master/Arduino/MPU6050/examples/IMU_Zero

- turn off the car

- connect the ardunio usb to your computer

- open serial port "sudo chmod 777 /dev/ttyUSB0"

- compile IMU_Zero library and program it on the ardunio

- using "sudo minicom" see the output of the program

- wait 10 minutes and read the results.

- update your main.ino source based on the the numbers

```
    mpu.setXGyroOffset(420);
    mpu.setYGyroOffset(-59);
    mpu.setZGyroOffset(69);
    mpu.setZAccelOffset(1323); 
```

- compile again the main.ino and program it to the arduino

- disconnect the arduino, test the car again with the 200 rpm.

- let me know if works now!

**Comment by Toku11** [comment]
Thanks for your help, the IMU works fine with the values given by IMU_ZERO.
