### ISSUE TITLE
Autostart

### ISSUE THREAD

**Issue by JustMeOnLine** [AutoModelCar/AutoModelCarWiki#6]
I cannot auto launch another file. I comment the line "manual_control manual_odroid.launch" and write my launch file and do not launch the nodes in the file. I do not know how to do it. It gives me the error "ERROR: Unable to communicate with master !". The packages are in catkin_ws_user. Thanks in advance.

**Comment by ZahraBoroujeni** [comment]
Write the line below in autostart.sh or at the end of ~/bashrc.sh
source ~/catkin_ws_user/devel/setup.bash
