### ISSUE TITLE
librealsense, set2.sh, system frozen

### ISSUE THREAD

**Issue by JLMundoG** [AutoModelCar/AutoModelCarWiki#8]
Hello

I was flashing eMMC following the guide and had the same problem here with set2.sh and librealsense [https://github.com/AutoModelCar/AutoModelCarWiki/issues/7], I used the solution  and works, So and tried to reboot and System freezes during boot.

After many Attempts to booting, i flashing again the eMMC and again had the problem with librealsense and the system freeze.

Any idea how to solve it?

Note: using the solution to compile, the Realsense camera still did not work.

**Comment by Toku11** [comment]
Copy to the odroid without  sudo ... just scp ... the lines in set2

**Comment by AutoModelCar** [comment]
I updated copy.sh file and remove all "sudo". It should work now.
