### ISSUE TITLE
Is there something like teleop_key node for the car?

### ISSUE THREAD

**Issue by eduardomtz** [AutoModelCar/AutoModelCarWiki#9]
And if so, whats its name?

Thanks

**Comment by AutoModelCar** [comment]
You can use xbox joystick, using http://wiki.ros.org/joy node. 
@SGSSGene : Simon do you have any tested package?

**Comment by SGSSGene** [comment]
I don't know of any package that does something like you probably expect from teleop_key.

The joy_node can only be run on a laptop/desktop pc. It will not work on the car. The kernel is missing the drivers for any type of joystick input device.

**Comment by eduardomtz** [comment]
Well my idea is to control the car from a PC, just to record a couple of ROS bags, and I thought that this could help me: manual_PC.launch but it does not or i don't know how it works 

Having launched the joy node on a PC, what launch file do i have to run on the car? in order to control the car with the joystick

Thanks

**Comment by SGSSGene** [comment]
Hi,
sorry. No launch file exists.

The feature you requested should be quite easy to implement. We'd be happy to except a pull request for such a feature or see new packages on github for this.

**Comment by eduardomtz** [comment]
Absolutely, if we find the time to implement it, we will be happy to contribute.

Thanks you for your attention.

**Comment by noelcortes** [comment]
You can use our teleop node for the car. This node uses a xbox 360 usb controller, but it can be adapted to other kind of usb controllers from the launch file. First, you need to setup a simple ROS network from the odroid computer (master) and your laptop (with the usb controller) so... u will launch the sensors and actuators in the car and run the joy and teleop nodes in your computer...

teleop node src:
https://github.com/noelcortes/joystick-control/blob/master/joy_teleop.cpp

launch file:
https://github.com/noelcortes/joystick-control/blob/master/controller.launch

For setup the ros network:
http://wiki.ros.org/ROS/NetworkSetup

Joy package installation and info:
http://wiki.ros.org/joy/Tutorials/ConfiguringALinuxJoystick

Regards.
